### PR TITLE
Schema: formalize connect.capabilities message format

### PR DESCRIPTION
**Pull request by Cahb**
Capabilities message is unregulated as of now;
Formalize the layout by introducing yml file.

### CODE REVIEW

**Comment by Cahb** [comment]
Hi @phwhite @mikehansen1970
I know this PR and commit was reviewed already internally on the HLD page (Tip confl), however, the reason for this review in particular is to agree upon the following problem: under **which file exactly** the connect.capabilities schema yml file should be merged? As it won't be used by any of the parsers, and the file is more of a formal one to formalize the layout of capabilities?

**Comment by mikehansen1970** [comment]
> Hi @phwhite @mikehansen1970 I know this PR and commit was reviewed already internally on the HLD page (Tip confl), however, the reason for this review in particular is to agree upon the following problem: under **which file exactly** the connect.capabilities schema yml file should be merged? As it won't be used by any of the parsers, and the file is more of a formal one to formalize the layout of capabilities?

Perhaps a different folder altogether then, for sake of keeping things organized.
For example, at the root level of the ols-ucentral-schema, similar to how there is a state and a schema folder, you could have a capabilities folder. At present it may just have the one file, but it would still make sense to do it this way, as it is not part of schema or state. 
That's my recommendation. However, as long as it exists, I am fine with other choices.

**Review by mikehansen1970 — COMMENTED** [review]
As mentioned in comments, perhaps it's own folder.

**Comment by phwhite** [comment]
@Cahb I like @mikehansen1970 suggestion of putting it into a new/separate capabilities folder.   What do you think of this?

**Comment by Cahb** [comment]
@phwhite @mikehansen1970 thanks for your replies, guys;
Repushed with your comments taken into consideration;

**Review by phwhite — APPROVED** [review]

**Pull request merged**
